### ISSUE TITLE
Suggestions to improve

### ISSUE THREAD

**Issue by Cmurilochem** [esciencecenter-digital-skills/NEBULA-content-template#1]
Hi @JaroCamphuijsen and @raar1.
I have made this repo template that allows one to create custom lessons and deploy it with NEBULA. It is for now quite simple; it updates automatically the `config.json` file (`"repoName"`) through a specific GitHub actions workflow [generate_config.yml](https://github.com/esciencecenter-digital-skills/NEBULA-content-template/blob/main/.github/workflows/generate_config.yml) that runs only once after the instantiation of your repo from the template.

I guess that this still deserves some adjustments that should follow with further developments with NEBULA. But for now any suggestion to improve is very welcome!
Thanks

**Comment by JaroCamphuijsen** [comment]
I think we can close this issue and add new issues for each suggestion once suggestions arise.
